[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "mdai"
author = "MD.ai"
author-email = "github@md.ai"
home-page = "https://www.md.ai"
classifiers = ["License :: OSI Approved :: Apache Software License"]

