[tool.black]
line-length = 100

[tool.poetry]
name = "mdai-client-py"
version = "0.4.1"
description = "MD.ai DICOM proxy for deployment within firewalled network"
authors = ["Leon Chen <leon@md.ai>"]

[tool.poetry.dependencies]
python = ">=3.7"
arrow = "*"
matplotlib = "*"
numpy = "*"
opencv-python ="*"
pandas = "*"
pillow = "*"
pydicom = "*"
requests = "*"
retrying = "*"
scikit-image = "*"
tqdm = "*"

[tool.poetry.dev-dependencies]
black = "==19.3b0"
flake8 = "*"
pytest = "*"
sphinx = "^2.2"
recommonmark = "^0.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
